# Default values for webapp

replicaCount: 3

image:
  repository: 586794450782.dkr.ecr.us-east-1.amazonaws.com/my-webapp
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # Example:
  # fsGroup: 2000

securityContext: {}
  # Example:
  # runAsUser: 1000
  # runAsNonRoot: true
  # readOnlyRootFilesystem: true
  # capabilities:
  #   drop:
  #   - ALL

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 120m
    memory: 180Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: config
#   configMap:
#     name: my-config

volumeMounts: []
# - name: config
#   mountPath: /etc/config
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
